# Generated by Django 5.0 on 2024-01-17 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoulsBackendApp', '0010_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendingUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='members_present',
            field=models.ManyToManyField(blank=True, related_name='attendances', to='SoulsBackendApp.attendinguser'),
        ),
        migrations.AlterField(
            model_name='smallgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='small_groups', to='SoulsBackendApp.attendinguser'),
        ),
    ]
