# Generated by Django 5.0 on 2024-01-17 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoulsBackendApp', '0011_attendinguser_alter_attendance_members_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendinguser',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
