# Generated by Django 5.0 on 2024-01-18 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoulsBackendApp', '0012_alter_attendinguser_name_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='id_deleted',
            new_name='is_deleted',
        ),
    ]
