# Generated by Django 5.0 on 2024-01-19 00:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoulsBackendApp', '0013_rename_id_deleted_attendance_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
