# Generated by Django 5.0 on 2024-01-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoulsBackendApp', '0014_organization_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='week_number',
            field=models.IntegerField(default=3),
        ),
    ]
