# Generated by Django 5.0 on 2024-01-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoulsBackendApp', '0015_attendance_week_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='week_number',
            field=models.IntegerField(),
        ),
    ]
